# Docker Compose
# https://docs.docker.com/compose/
# Usage: docker-compose up
---
version: "3"
services:

  app:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
    environment: &environment
      - STAGE=local
    volumes:
      - .:/usr/src
    build:
      args:
        version: 0.0.0
    env_file:
      - .env
