# Docker Compose
# https://docs.docker.com/compose/
# Usage: docker-compose up
---
version: "3"
services:

  app:
    ports:
      - "1313:1313"
    environment: &environment
      - STAGE=local
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
    volumes:
      - .:/usr/src
    env_file:
      - .env
