title = "gitleaks config"

[[rules]]
    description = "AWS Access Key"
    regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
    tags = ["key", "AWS"]
    [rules.allowlist]
        description = "ignore value fake"
        regexes = [
            '''AIDAQEAAAAAAAAAAAAAA''',
        ]

[[rules]]
    description = "AWS cred file info"
    regex = '''(?i)(aws_access_key_id|aws_secret_access_key)(.{0,20})?=.[0-9a-zA-Z\/+]{20,40}'''
    tags = ["AWS"]

[[rules]]
    description = "AWS Secret Key"
    regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
    tags = ["key", "AWS"]

[[rules]]
    description = "AWS MWS key"
    regex = '''amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'''
    tags = ["key", "AWS", "MWS"]

[[rules]]
  description = "Facebook Secret Key"
  regex = '''(?i)(facebook|fb)(.{0,20})?(?-i)['\"][0-9a-f]{32}['\"]'''
  tags = ["key", "Facebook"]

[[rules]]
  description = "Facebook Client ID"
  regex = '''(?i)(facebook|fb)(.{0,20})?['\"][0-9]{13,17}['\"]'''
  tags = ["key", "Facebook"]

[[rules]]
  description = "Facebook access token"
  regex = '''EAACEdEose0cBA[0-9A-Za-z]+'''
  tags = ["key", "Facebook"]

[[rules]]
    description = "Twitter Secret Key"
    regex = '''(?i)twitter(.{0,20})?['\"][0-9a-z]{35,44}['\"]'''
    tags = ["key", "Twitter"]

[[rules]]
    description = "Twitter Client ID"

    regex = '''(?i)twitter(.{0,20})?['\"][0-9a-z]{18,25}['\"]'''
    tags = ["client", "Twitter"]

[[rules]]
    description = "Github"
    regex = '''(?i)github(.{0,20})?(?-i)['\"][0-9a-zA-Z]{35,40}['\"]'''
    tags = ["key", "Github"]

[[rules]]
    description = "LinkedIn Client ID"
    regex = '''(?i)linkedin(.{0,20})?(?-i)['\"][0-9a-z]{12}['\"]'''
    tags = ["client", "LinkedIn"]

[[rules]]
    description = "LinkedIn Secret Key"
    regex = '''(?i)linkedin(.{0,20})?['\"][0-9a-z]{16}['\"]'''
    tags = ["secret", "LinkedIn"]

[[rules]]
    description = "Slack"
    regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''
    tags = ["key", "Slack"]

[[rules]]
    description = "EC"
    regex = '''-----BEGIN EC PRIVATE KEY-----'''
    tags = ["key", "EC"]

[[rules]]
    description = "Google API key"
    regex = '''AIza[0-9A-Za-z\\-_]{35}'''
    tags = ["key", "Google"]

[[rules]]
  description = "Google Cloud Platform API key"
  regex = '''(?i)(google|gcp|youtube|drive|yt)(.{0,20})?['\"][AIza[0-9a-z\\-_]{35}]['\"]'''
  tags = ["key", "Google", "GCP"]

[[rules]]
  description = "Google OAuth"
  regex = '''(?i)(google|gcp|auth)(.{0,20})?['"][0-9]+-[0-9a-z_]{32}\.apps\.googleusercontent\.com['"]'''
  tags = ["key", "Google", "OAuth"]

[[rules]]
  description = "Google OAuth access token"
  regex = '''ya29\.[0-9A-Za-z\-_]+'''
  tags = ["key", "Google", "OAuth"]

[[rules]]
    description = "Heroku API key"
    regex = '''(?i)heroku(.{0,20})?['"][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}['"]'''
    tags = ["key", "Heroku"]

[[rules]]
    description = "MailChimp API key"
    regex = '''(?i)(mailchimp|mc)(.{0,20})?['"][0-9a-f]{32}-us[0-9]{1,2}['"]'''
    tags = ["key", "Mailchimp"]

[[rules]]
    description = "Mailgun API key"
    regex = '''(?i)(mailgun|mg)(.{0,20})?['"][0-9a-z]{32}['"]'''
    tags = ["key", "Mailgun"]

[[rules]]
    description = "PayPal Braintree access token"
    regex = '''access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}'''
    tags = ["key", "Paypal"]

[[rules]]
    description = "Picatic API key"
    regex = '''sk_live_[0-9a-z]{32}'''
    tags = ["key", "Picatic"]

[[rules]]
    description = "Slack Webhook"
    regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}'''
    tags = ["key", "slack"]

[[rules]]
    description = "Stripe API key"
    regex = '''(?i)stripe(.{0,20})?['\"'][sk|rk]_live_[0-9a-zA-Z]{24}'''
    tags = ["key", "Stripe"]

[[rules]]
    description = "Square access token"
    regex = '''sq0atp-[0-9A-Za-z\-_]{22}'''
    tags = ["key", "square"]

[[rules]]
    description = "Square OAuth secret"
    regex = '''sq0csp-[0-9A-Za-z\\-_]{43}'''
    tags = ["key", "square"]

[[rules]]
    description = "Twilio API key"
    regex = '''(?i)twilio(.{0,20})?['\"][0-9a-f]{32}['\"]'''
    tags = ["key", "twilio"]

[[rules]]
  description = "Password in URL"
  regex = '''[a-zA-Z]{3,10}:\/\/[^\/\s:@]{3,20}:[^\/\s:@]{3,20}@.{1,100}\/?.?'''
  tags = ["key", "URL", "generic"]


[[rules]]
    description = "Env Var"
    regex = '''(?i)(apikey|secret|key|api|password|pass|pw|host)=[0-9a-zA-Z-_.{}]{4,120}'''
    tags = ["env"]
    [rules.allowlist]
        description = "ignore value fake"
        regexes = [
            '''host=HOST''',
        ]

[[rules]]
    description = "Email"
    regex = '''[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}'''
    tags = ["email"]
    [rules.allowlist]
        description = "ignore emails"
        regexes = [
            '''[a-zA-Z0-9._%+-]+@users.noreply.github.com''',
            '''[a-zA-Z0-9._%+-]+@yopmail.com''',
            '''git@github.com''',
            '''git@gitlab.com''',
            '''slovacus@gmail.com''',
            '''luis@hadenlabs.com''',
            '''hola@hadenlabs.com''',
            '''hello@hadenlabs.com''',
            '''support@hadenlbas.com''',
            '''support@hadenlabs.com''',
            '''dum-u@hadenlabs.com''',
        ]

[[rules]]
    description = "High Entropy"
    regex = '''[0-9a-zA-Z-_!{}/=]{4,120}'''
    file = '''(?i)(dump.sql|high-entropy-misc.txt)$'''
    tags = ["entropy"]
    [[rules.Entropies]]
        Min = "4.3"
        Max = "7.0"
    [rules.allowlist]
        description = "ignore some"
        files = ['''(.*pub|env)$''']
        paths = ['''(security.*)''']

[[rules]]
    description = "Potential bash var"
    regex='''(?i)(=)([0-9a-zA-Z-_!{}=]{4,120})'''
    tags = ["key", "bash", "API", "generic"]
        [[rules.Entropies]]
            Min = "3.5"
            Max = "4.5"
            Group = "1"

[[rules]]
    description = "WP-Config"
    regex='''define(.{0,20})?(DB_CHARSET|NONCE_SALT|LOGGED_IN_SALT|AUTH_SALT|NONCE_KEY|DB_HOST|DB_PASSWORD|AUTH_KEY|SECURE_AUTH_KEY|LOGGED_IN_KEY|DB_NAME|DB_USER)(.{0,20})?['|"'].{10,120}['|"']'''
    tags = ["key", "API", "generic"]

[[rules]]
  description = "Generic API Key"
  regex = '''[a|A][p|P][i|I][_]?[k|K][e|E][y|Y].*['|\"][0-9a-zA-Z]{32,45}['|\"]'''

[[rules]]
  description = "Generic Secret"
  regex = '''[s|S][e|E][c|C][r|R][e|E][t|T].*['|\"][0-9a-zA-Z]{32,45}['|\"]'''


[[rules]]
    description = "Files with keys and credentials"
    file = '''(?i)(id_rsa|passwd|id_rsa.pub|pgpass)$'''
    tags = ["key", "files"]

[[rules]]
    description = "Extension Files with keys and credentials"
    file = '''(.*?)(pub|pem|ppk|key)$'''
    tags = ["key", "files"]

# Global allowlist
[allowlist]
  description = "Whitelisted files"
  files = [
    '''(.*?)(jpg|gif|png|doc|pdf|bin|mp3|mp4|mov|ttf|woff|woff2|eot|lock)$''',
    '''^\.gitignore$''',
    '''^\.gitleaks.toml$''',
    '''^yarn.lock$''',
    '''^vendor/(.*?)$''',
    '''^node_modules/(.*?)$''',
  ]
  commits =[
    '''00d84ebfafd405a73c2db313191d1ac192f7ecf7''',
    '''30d7a56ca329955e6299a9cf3cc232d8f5d6de10''',
    '''71900238fc8408d761f70ea60ecc35247acbf6d6''',
    '''73f3e37c54f4af70891c500c358ebc80f40b99f5''',
    '''7f7180f77b3a59d18466b5307e384d671b080346''',
    '''8c361871cb7e34a7df0a90b6055cccab9614067e''',
    '''93d15eb74dfcf52923df8280fa9aa67ccdd2a96f''',
    '''a19cac0f29404f3f03251d071548a9c7c27938e0''',
    '''a6c34a8074f08d9ccb0c1b2c0743b72ed9bad098''',
    '''ada0090668bb15a28e4a45a731b5252d75e110b3''',
    '''bc23dd17e63b6779b7817d167c6c4cd657d2ed3e''',
    '''c41c18a009f854393a4c470e5844109aeee3e885''',
    '''d05c0b9aeab0d9199db18abc94c9e898f8d6a603''',
    '''d961826de54b08e23794933e86358d70ac97d906''',
    '''e11acb5401dd8785cbfe803a6757a2b760c252ef''',
    '''efa6e6d346c024f27232d65533504dcc1f47419f''',
    '''f33c466accca2aab04b57ecf8cf4178f352acd65''',
    '''f490973517286d4187db61d5ce26892aa0283bfd''',
    '''fcc39328edfc87b9bff762c3dc3d554cf070017f''',
  ]


[whitelist]
  description = "image and html allowlists"
	files = [
    '''(.*?)(jpg|gif|png|doc|pdf|bin|mp3|mp4|mov|ttf|woff|woff2|eot|lock)$''',
    '''^\.gitleaks.toml$''',
    '''^\.gitignore$''',
    '''^yarn.lock$''',
  ]
