# Docker Compose
# https://docs.docker.com/compose/

version: '3.6'
services:
  # Python
  app:
    environment: &environment
      - STAGE=dev
    image: luismayta.github.io-app-dev
    build:
      args:
        stage: dev

  nodejs:
    restart: always
    image: luismayta.github.io-node-dev
    build:
      args:
        stage: dev
    volumes:
      - .:/usr/src
      - yarn-cache:/root/.yarn-cache
    env_file:
      - .env

  check:
    image: luismayta.github.io-check-dev
    environment: *environment
    build:
      context: .
      dockerfile: provision/docker/check/Dockerfile
      args:
        stage: dev
    volumes:
      - .:/usr/src
    env_file:
      - .env
