# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

version: "3"
services:
  app:
    image: luismayta.github.io-app-test:0.0.0
    environment: &environment
      - FLASK_CONFIG=testing
    build:
      args:
        stage: test
        version: 0.0.0
    volumes:
      - .:/usr/src
