name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v2

      - name: Get Theme
        run: git submodule update --init --recursive

      - name: Update theme to latest commit
        run: git submodule update --remote --merge

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.80.0
          TARGET_REPO: luismayta/luismayta.github.io
          TARGET_BRANCH: gh-pages
          TOKEN: ${{ secrets.GH_TOKEN }}
          CNAME: luismayta.github.io
